task:
  name: nightly x86_64-unknown-freebsd-13
  freebsd_instance:
    image_family: freebsd-13-2
  setup_script:
    - pkg install -y curl ssl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain nightly --profile=minimal
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all-features

task:
  name: nightly x86_64-unknown-freebsd-14
  freebsd_instance:
    image_family: freebsd-14-0
  setup_script:
    - pkg install -y curl ssl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain nightly --profile=minimal
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all-features
